version: '3.1'
services:
  db:
    image: mysql
    container_name: sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3307:3307"
    volumes:
    - web/var/lib/mysql

volumes:
  web_data:
